on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: npm install

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: steelballs.com.ua
        username: qtqzgjpe
        password: ${{ secrets.ftp_password }}
        local-dir: ./app/
        server-dir: /githubactions.steelballs.com.ua/
        exclude: .git*
          - .git*/**
          - node_modules/**
          - node_modules/**/*